global:
  domain: admin-argocd.sctp-sandbox.com
# configs:
#   # params: 
#   #   "server.insecure": true

server:
  ingress:
    enabled: true
    ingressClassName: nginx
    annotations:
      cert-manager.io/cluster-issuer: "letsencrypt-prod"
      external-dns.alpha.kubernetes.io/hostname: "admin-argocd.sctp-sandbox.com"
      nginx.ingress.kubernetes.io/ssl-passthrough: "true"
      nginx.ingress.kubernetes.io/backend-protocol: "HTTPS"
    tls: true