# Use this workflow only if the Github OIDC role to create the cluster has been deleted (create-cluster.yml)
# This workflow creates the OIDC role for the deployer to create the cluster and deploy the addons
name: Create Deployer Role

on: workflow_dispatch

env:            
  AWS_REGION: ap-southeast-1  

jobs:
  Create-Deployer-Role:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v3
    
    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: ${{ env.AWS_REGION }}

    - name: Setup Terraform
      uses: hashicorp/setup-terraform@v2

    - name: Terraform fmt
      run: terraform fmt --recursive
    
    - name: Terraform Init
      run: terraform init
      working-directory: ./terraform/eks-cluster-deployer-role

    - name: Terraform Plan
      run: terraform plan
      working-directory: ./terraform/eks-cluster-deployer-role

    - name: Terraform Apply
      run: terraform apply --auto-approve
      working-directory: ./terraform/eks-cluster-deployer-role
